name: segment_tree
description: A lightweight Segment Tree in Dart.
version: 2.0.0
homepage: https://www.github.com/modulovalue/dart_segment_tree
issue_tracker: https://github.com/modulovalue/dart_segment_tree/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # TODO remove this
  ffi:

dev_dependencies:
  extra_pedantic: ^2.0.0
  test: ^1.20.2
